# Generated by Django 2.0.2 on 2019-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'ProyectoCategoria',
                'verbose_name_plural': 'ProyectoCategorias',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.ProjectCategory', verbose_name='Categoria'),
        ),
    ]
