# Generated by Django 2.0.2 on 2019-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190730_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='metadata',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TagName'),
        ),
    ]
