# Generated by Django 2.0.2 on 2019-07-30 22:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectcategory_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
    ]
