# Generated by Django 2.0.2 on 2019-08-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.ManyToManyField(to='portfolio.ProjectCategory', verbose_name='Categoria'),
        ),
    ]
